
jwt:
  secret: '********'

server:
  port: 9898

spring:
  datasource:
    username: ovrsamhv
    password: 6sa5mkueOLo_KyixzboGZHHVRKAJRWOo
    url: jdbc:postgresql://ruby.db.elephantsql.com/ovrsamhv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
#    mail:
#      host: localhost
#      port: 9898
#      username: hello
#      password: hello
#
#      properties:
#        mail:
#          smtp:
#            ssl:
#              trust: "*"
#            auth: true
#            starttls:
#              enable: true
#            connectiontimeout: 5000tt
#            timeout: 3000
#            writetimeout: 5000
